global:
  resolve_timeout: 5m

route:
  receiver: webhook
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: webhook
    webhook_configs:
      - url: '{{ env "ALERT_WEBHOOK_URL" }}'
        send_resolved: true
